// Auto-generated from iphoneSpecs.json
export interface IphoneSpec {
  productId: string;
  name: string;
  brand: string;
  category: string;
  subCategory: string;
  shortModel: string;
  model: string;
  storages: string[];
  storageCodes?: { [key: string]: string };
  colors: string[];
  colorCodes?: { [key: string]: string };
  regions: string[];
  regionCodes?: { [key: string]: string };
  conditions: string[];
  conditionCodes?: { [key: string]: string };
  status: string;
}

const rawIphoneSpecs: Array<Omit<IphoneSpec, 'productId' | 'name'>> = [
  {
  "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 6",
    "shortModel":"IP6",
    "storages":["16GB","32GB","64GB","128GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64", "128GB": "128" },
    "colors":["Space Gray","Silver","Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD"},
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 6 Plus",
    "shortModel":"IP6P",
    "storages":["16GB","32GB","64GB","128GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64", "128GB": "128" },
    "colors":["Space Gray","Silver","Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD"},
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 6S",
    "shortModel":"IP6S",
    "storages":["16GB","32GB","64GB","128GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64", "128GB": "128" },
    "colors":["Space Gray","Silver","Gold","Rose Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Rose Gold": "RGD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 6S Plus",
    "shortModel":"IP6SP",
    "storages":["16GB","32GB","64GB","128GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64", "128GB": "128" },
    "colors":["Space Gray","Silver","Gold","Rose Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Rose Gold": "RGD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 7",
    "shortModel":"IP7",
    "storages":["32GB","128GB","256GB"],
      "storageCodes": { "32GB": "32", "128GB": "128", "256GB": "256" },
    "colors":["Black","Jet Black","Silver","Gold","Rose Gold"],
      "colorCodes": { "Black": "BLK", "Jet Black": "JBLK", "Silver": "SLV", "Gold": "GLD", "Rose Gold": "RGD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 7 Plus",
    "shortModel":"IP7P",
    "storages":["32GB","128GB","256GB"],
      "storageCodes": { "32GB": "32", "128GB": "128", "256GB": "256" },
    "colors":["Black","Jet Black","Silver","Gold","Rose Gold"],
      "colorCodes": { "Black": "BLK", "Jet Black": "JBLK", "Silver": "SLV", "Gold": "GLD", "Rose Gold": "RGD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 8",
    "shortModel":"IP8",
    "storages":["64GB","256GB"],
      "storageCodes": { "64GB": "64", "256GB": "256" },
    "colors":["Space Gray","Silver","Gold","Red"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Red": "RED" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 8 Plus",
    "shortModel":"IP8P",
    "storages":["64GB","256GB"],
      "storageCodes": { "64GB": "64", "256GB": "256" },
    "colors":["Space Gray","Silver","Gold","Red"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Red": "RED" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone X",
    "shortModel":"IPX",
    "storages":["64GB","256GB"],
      "storageCodes": { "64GB": "64", "256GB": "256" },
    "colors":["Space Gray","Silver"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone XS",
    "shortModel":"IPXS",
    "storages":["64GB","256GB","512GB"],
      "storageCodes": { "64GB": "64", "256GB": "256", "512GB": "512" },
    "colors":["Space Gray","Silver","Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone XS Max",
    "shortModel":"IPXSM",
    "storages":["64GB","256GB","512GB"],
      "storageCodes": { "64GB": "64", "256GB": "256", "512GB": "512" },
    "colors":["Space Gray","Silver","Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone XR",
    "shortModel":"IPXR",
    "storages":["64GB","128GB","256GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256" },
    "colors":["Black","White","Blue","Yellow","Coral","Red"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Yellow": "YLW", "Coral": "CRL", "Red": "RED" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 11",
    "shortModel":"IP11",
    "storages":["64GB","128GB","256GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256" },
    "colors":["Black","White","Green","Yellow","Purple","Red"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Green": "GRN", "Yellow": "YLW", "Purple": "PRP", "Red": "RED" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 11 Pro",
    "shortModel":"IP11P",
    "storages":["64GB","256GB","512GB"],
      "storageCodes": { "64GB": "64", "256GB": "256", "512GB": "512" },
    "colors":["Space Gray","Silver","Gold","Midnight Green"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Midnight Green": "MDG" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 11 Pro Max",
    "shortModel":"IP11PM",
    "storages":["64GB","256GB","512GB"],
      "storageCodes": { "64GB": "64", "256GB": "256", "512GB": "512" },
    "colors":["Space Gray","Silver","Gold","Midnight Green"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Midnight Green": "MDG" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 12",
    "shortModel":"IP12",
    "storages":["64GB","128GB","256GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256" },
    "colors":["Black","White","Red","Green","Blue","Purple"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Red": "RED", "Green": "GRN", "Blue": "BLU", "Purple": "PRP" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 12 Pro",
    "shortModel":"IP12P",
    "storages":["128GB","256GB","512GB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Graphite","Silver","Gold","Pacific Blue"],
      "colorCodes": { "Graphite": "GRF", "Silver": "SLV", "Gold": "GLD", "Pacific Blue": "PBL" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 12 Pro Max",
    "shortModel":"IP12PM",
    "storages":["128GB","256GB","512GB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Graphite","Silver","Gold","Pacific Blue"],
      "colorCodes": { "Graphite": "GRF", "Silver": "SLV", "Gold": "GLD", "Pacific Blue": "PBL" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 12 Mini",
    "shortModel":"IP12M",
    "storages":["64GB","128GB","256GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256" },
    "colors":["Black","White","Red","Green","Blue","Purple"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Red": "RED", "Green": "GRN", "Blue": "BLU", "Purple": "PRP" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 13",
    "shortModel":"IP13",
    "storages":["128GB","256GB","512GB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Midnight","Starlight","Blue","Pink","Red","Green"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Blue": "BLU", "Pink": "PNK", "Red": "RED", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 13 Pro",
    "shortModel":"IP13P",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Graphite","Silver","Gold","Sierra Blue"],
      "colorCodes": { "Graphite": "GRF", "Silver": "SLV", "Gold": "GLD", "Sierra Blue": "SRB" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 13 Pro Max",
    "shortModel":"IP13PM",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Graphite","Silver","Gold","Sierra Blue"],
      "colorCodes": { "Graphite": "GRF", "Silver": "SLV", "Gold": "GLD", "Sierra Blue": "SRB" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 13 Mini",
    "shortModel":"IP13M",
    "storages":["128GB","256GB","512GB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Midnight","Starlight","Blue","Pink","Red","Green"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Blue": "BLU", "Pink": "PNK", "Red": "RED", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 14",
    "shortModel":"IP14",
    "storages":["128GB","256GB","512GB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Midnight","Starlight","Blue","Purple","Red","Yellow","Green"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Blue": "BLU", "Purple": "PRP", "Red": "RED", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 14 Pro",
    "shortModel":"IP14P",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Deep Purple","Silver","Gold","Space Black"],
      "colorCodes": { "Deep Purple": "DPR", "Silver": "SLV", "Gold": "GLD", "Space Black": "SPB" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 14 Mini",
    "shortModel":"IP14M",
    "storages":["128GB","256GB","512GB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Midnight","Starlight","Blue","Purple","Red","Yellow","Green"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Blue": "BLU", "Purple": "PRP", "Red": "RED", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 14 Pro Max",
    "shortModel":"IP14PM",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Deep Purple","Silver","Gold","Space Black"],
      "colorCodes": { "Deep Purple": "DPR", "Silver": "SLV", "Gold": "GLD", "Space Black": "SPB" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
    {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 15",
    "shortModel":"IP15",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black","White","Blue","Pink","Yellow","Green"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Pink": "PNK", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 15 Plus",
    "shortModel":"IP15P",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black","White","Blue","Pink","Yellow","Green"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Pink": "PNK", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 15 Pro",
    "shortModel":"IP15P",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black Titanium","Silver Titanium","Blue Titanium","Natural Titanium"],
      "colorCodes": { "Black Titanium": "BLT", "Silver Titanium": "SLT", "Blue Titanium": "BLT", "Natural Titanium": "NLT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 15 Pro Max",
    "shortModel":"IP15PM",
    "storages":["256GB","512GB","1TB","2TB"],
      "storageCodes": { "256GB": "256", "512GB": "512", "1TB": "1T", "2TB": "2T" },
    "colors":["Black Titanium","Silver Titanium","Blue Titanium","Natural Titanium"],
      "colorCodes": { "Black Titanium": "BLT", "Silver Titanium": "SLT", "Blue Titanium": "BLT", "Natural Titanium": "NLT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone SE (5th Gen)",
    "shortModel":"IPSE5",
    "storages":["64GB","128GB","256GB","512GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Midnight","Starlight","Red","Blue","Purple","Green"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Red": "RED", "Blue": "BLU", "Purple": "PRP", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone SE (4th Gen)",
    "shortModel":"IPSE4",
    "storages":["64GB","128GB","256GB","512GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256", "512GB": "512" },
    "colors":["Midnight","Starlight","Red","Blue","Purple"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Red": "RED", "Blue": "BLU", "Purple": "PRP" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone SE (3rd Gen)",
    "shortModel":"IPSE3",
    "storages":["64GB","128GB","256GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256" },
    "colors":["Midnight","Starlight","Red"],
      "colorCodes": { "Midnight": "MDN", "Starlight": "STL", "Red": "RED" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone SE (2nd Gen)",
    "shortModel":"IPSE2",
    "storages":["64GB","128GB","256GB"],
      "storageCodes": { "64GB": "64", "128GB": "128", "256GB": "256" },
    "colors":["Black","White","Red"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Red": "RED" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone SE (1st Gen)",
    "shortModel":"IPSE1",
    "storages":["16GB","32GB","64GB","128GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64", "128GB": "128" },
    "colors":["Space Gray","Silver","Gold","Rose Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD", "Rose Gold": "RGD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },{
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 5S",
    "shortModel":"IP5S",
    "storages":["16GB","32GB","64GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64" },
    "colors":["Space Gray","Silver","Gold"],
      "colorCodes": { "Space Gray": "SPG", "Silver": "SLV", "Gold": "GLD" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 5C",
    "shortModel":"IP5C",
    "storages":["8GB","16GB","32GB"],
      "storageCodes": { "8GB": "8", "16GB": "16", "32GB": "32" },
    "colors":["White","Pink","Yellow","Blue","Green"],
      "colorCodes": { "White": "WHT", "Pink": "PNK", "Yellow": "YLW", "Blue": "BLU", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 5",
    "shortModel":"IP5",
    "storages":["16GB","32GB","64GB"],
      "storageCodes": { "16GB": "16", "32GB": "32", "64GB": "64" },
    "colors":["Black","White"],
      "colorCodes": { "Black": "BLK", "White": "WHT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 4S",
    "shortModel":"IP4S",
    "storages":["8GB","16GB","32GB","64GB"],
      "storageCodes": { "8GB": "8", "16GB": "16", "32GB": "32", "64GB": "64" },
    "colors":["Black","White"],
      "colorCodes": { "Black": "BLK", "White": "WHT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 4",
    "shortModel":"IP4",
    "storages":["8GB","16GB","32GB"],
      "storageCodes": { "8GB": "8", "16GB": "16", "32GB": "32" },
    "colors":["Black","White"],
      "colorCodes": { "Black": "BLK", "White": "WHT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 3GS",
    "shortModel":"IP3GS",
    "storages":["8GB","16GB","32GB"],
      "storageCodes": { "8GB": "8", "16GB": "16", "32GB": "32" },
    "colors":["Black","White"],
      "colorCodes": { "Black": "BLK", "White": "WHT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 3G",
    "shortModel":"IP3G",
    "storages":["8GB","16GB"],
      "storageCodes": { "8GB": "8", "16GB": "16" },
    "colors":["Black","White"],
      "colorCodes": { "Black": "BLK", "White": "WHT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone",
    "shortModel":"IP1",
    "storages":["4GB","8GB","16GB","32GB"],
      "storageCodes": { "4GB": "4", "8GB": "8", "16GB": "16", "32GB": "32" },
    "colors":["Black","White"],
      "colorCodes": { "Black": "BLK", "White": "WHT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 16",
    "shortModel":"IP16",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black","White","Blue","Pink","Yellow","Green"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Pink": "PNK", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 16 Pro",
    "shortModel":"IP16P",
    "storages":["128GB","256GB","512GB","1TB","2TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T", "2TB": "2T" },
    "colors":["Black Titanium","Silver Titanium","Blue Titanium","Natural Titanium"],
      "colorCodes": { "Black Titanium": "BLT", "Silver Titanium": "SLT", "Blue Titanium": "BLT", "Natural Titanium": "NLT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 16 Pro Max",
    "shortModel":"IP16PM",
    "storages":["256GB","512GB","1TB","2TB"],
      "storageCodes": { "256GB": "256", "512GB": "512", "1TB": "1T", "2TB": "2T" },
    "colors":["Black Titanium","Silver Titanium","Blue Titanium","Natural Titanium"],
      "colorCodes": { "Black Titanium": "BLT", "Silver Titanium": "SLT", "Blue Titanium": "BLT", "Natural Titanium": "NLT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 16 Plus",
    "shortModel":"IP16PL",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black","White","Blue","Pink","Yellow","Green"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Pink": "PNK", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 17",
    "shortModel":"IP17",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black","White","Blue","Pink","Yellow","Green"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Pink": "PNK", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 17 Pro",
    "shortModel":"IP17P",
    "storages":["128GB","256GB","512GB","1TB","2TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T", "2TB": "2T" },
    "colors":["Black Titanium","Silver Titanium","Blue Titanium","Natural Titanium"],
      "colorCodes": { "Black Titanium": "BLT", "Silver Titanium": "SLT", "Blue Titanium": "BLT", "Natural Titanium": "NLT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 17 Pro Max",
    "shortModel":"IP17PM",
    "storages":["256GB","512GB","1TB","2TB"],
      "storageCodes": { "256GB": "256", "512GB": "512", "1TB": "1T", "2TB": "2T" },
    "colors":["Black Titanium","Silver Titanium","Blue Titanium","Natural Titanium"],
      "colorCodes": { "Black Titanium": "BLT", "Silver Titanium": "SLT", "Blue Titanium": "BLT", "Natural Titanium": "NLT" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 17 Plus",
    "shortModel":"IP17PL",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Black","White","Blue","Pink","Yellow","Green"],
      "colorCodes": { "Black": "BLK", "White": "WHT", "Blue": "BLU", "Pink": "PNK", "Yellow": "YLW", "Green": "GRN" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  },
  {
    "brand":"Apple",
    "category":"Phone",
    "subCategory":"Goods for Sale",
    "model":"iPhone 17 Air",
    "shortModel":"IP17R",
    "storages":["128GB","256GB","512GB","1TB"],
      "storageCodes": { "128GB": "128", "256GB": "256", "512GB": "512", "1TB": "1T" },
    "colors":["Silver","Space Gray","Gold","Rose Gold","Blue","Pink"],
      "colorCodes": { "Silver": "SLV", "Space Gray": "SPG", "Gold": "GLD", "Rose Gold": "RGD", "Blue": "BLU", "Pink": "PNK" },
    "regions":["USA","Hong Kong","Australia","Singapore","China"],
      "regionCodes": { "USA": "LL", "Hong Kong": "ZA", "Australia": "XA", "Singapore": "ZP", "China": "CH" },
    "conditions":["USED"],
      "conditionCodes": { "USED": "U", "NEW": "N", "AUSED": "A" },
    "status":"Active"
  }  
];

export const iphoneSpecs: IphoneSpec[] = rawIphoneSpecs.map((spec) => ({
  productId: spec.shortModel,
  name: `${spec.brand} ${spec.model}`,
  ...spec,
}));

export const getIphoneSpecByModel = (model: string): IphoneSpec | undefined => {
  return iphoneSpecs.find(spec => spec.model === model);
};

export const getAvailableModels = (): string[] => {
  return iphoneSpecs.map(spec => spec.model);
};

export const getColorsByModel = (model: string): string[] => {
  const spec = getIphoneSpecByModel(model);
  return spec ? spec.colors : [];
};

export const getStoragesByModel = (model: string): string[] => {
  const spec = getIphoneSpecByModel(model);
  return spec ? spec.storages : [];
};

export const getRegionsByModel = (model: string): string[] => {
  const spec = getIphoneSpecByModel(model);
  return spec ? spec.regions : [];
};

export const getConditionsByModel = (model: string): string[] => {
  const spec = getIphoneSpecByModel(model);
  return spec ? spec.conditions : [];
};
